# this was useful: https://swimburger.net/blog/dotnet/how-to-deploy-aspnet-blazor-webassembly-to-github-pages
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: 5.0.x
      - name: Publish .NET Core Project
        run: dotnet publish WasmBoids/WasmBoids.csproj -c Release -o release --nologo
      - name: Add .nojekyll file # don't treat this as a Jekyll project
        run: touch release/wwwroot/.nojekyll
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: release/wwwroot
          
